### ISSUE TITLE
打开文件回到上次退出的行数有问题

### ISSUE THREAD

**Issue by wuxinxinggg** [bigeagle/neovim-config#2]
if has("autocmd")  " go back to where you exited
    autocmd BufReadPost *
    ¦   \ if line("'\"") > 0 && line ("'\"") <= line("$") |
    ¦   \   exe "normal g'\"" |
    ¦   \ endif
endif

**Comment by wuxinxinggg** [comment]
原因是家目录的.viminfo权限的问题，0建议改为1，如果在第一行就不用跳转了，默认不跳转就是第一行

**Comment by bigeagle** [comment]
-_-b
